.TH MARC 1.SH NAMEmarc \- merge arc archives.SH SYNOPSIS\fBmarc\fRtarget source [name ...].SH DESCRIPTION\fBmarc\fRcopies members from the arc archive\fIsource\fRinto\fItarget\fR,\fRall of them or only those named, without unpacking and packing themagain.  MARC 5.21, adapted to OS-9/68000 by Stephan Paschedag..SH SEE ALSOarc