.TH BPV 6 "17 Oct 1986".UC 4.SH NAMEbpv - tool for trek73.SH SYNOPSISbpv.SH DESCRIPTION.PP.I Bpvis a program used in conjunction with.I shipyard(6) to construct ships that can be used in the game.I trek73(6)..PP.IBpvprints out a list of the basic point values (BPV)of the four standard ship classes(DN, CA, CL, and DD)..PPThis allows a person using.I shipyard(6)to compare their ships with the standard ship classes..SH SEE ALSOtrek73(6).brJeff Okamoto,.I "The Star Trek Battle Manual".SH AUTHORJeff Okamoto.SH BUGSHopefully none.Bug reports should be sent to: ..!hplabs!hpccc!okamoto and ..!ucbvax!yee.