.TH SHIPYARD 6 "17 Oct 1986".UC 4.SH NAMEshipyard - Ship constructor for trek73.SH SYNOPSISshipyard.SH DESCRIPTION.PP.I Shipyardis a program to construct ships that can be used in the game.I trek73..PPThe user enters in the parameters for his new ship class.Once all of the parameters have been entered, the basic pointvalue (BPV) of the ship is printed out, as is its efficiency,turn rate, and maximum speed..PPIf these values are acceptable, the ship class is saved intothe user's home directory as.I .shipXX, where XX is the two-letter designation of the ship's class..SH FILES.TP$HOME/.trek??	Non-standard class ship.SH SEE ALSOtrek73(6).brJeff Okamoto,.I "The Star Trek Battle Manual".SH AUTHORJeff Okamoto.SH BUGSHopefully none.Bug reports should be sent to: ..!hplabs!hpccc!okamoto and ..!ucbvax!yee.