.TH WESTLEY 6.SH NAMEwestley \- loves me, loves me not.SH SYNOPSIS\fBwestley\fRpetals.SH DESCRIPTION\fBwestley 7\fRpulls seven petals from a daisy -- loves me, loves me not -- and sayshow it came out.  The 1990 International Obfuscated C Code Contest'sBest Layout: its source is written to be read as a love letter..SH SEE ALSOdds, theorem