.TH C4 6 "" "Local UNIX Programmer's Manual".SH NAMEc4 \- game of dropping pieces.SH SYNOPSIS.B c4.SH DESCRIPTION.I C4plays games of Connect Four\*R with you.You must use a CRT with cursor movement..PPThe columns are lettered from.B ato.BR g .You drop a piece into the board by picking a column.The first player to get four (or more) in a row wins.The program beeps when it threatens a winning move.Type.B qto quit, and control-L to redraw the screen..SH REMARKSHard to beat, but it never learns..SH AUTHORG. L. Sicherman  (att\^!\^windmill\^!\^gls)