.TH AREACODE 1.SH NAMEareacode \- look up telephone area codes.SH SYNOPSIS\fBareacode\fRcode ....SH DESCRIPTIONFor each North American area code given,\fBareacode\fRsays where it is, from a table of the late 1980s:.nf    Area code 212 is New York City (Manhattan and Bronx) New York.    Area code 999 is not a valid area code..fiCodes created since then are reported as not valid..SH NOTESNeeds Microware's\fBcio\fR.\fR