.TH FINGER 1.SH NAMEfinger \- show what the system knows about a user.SH SYNOPSIS\fBfinger\fRuser[@host].SH DESCRIPTION\fBfinger\fRlooks the user up in the password file and prints the account'sexecution and home directories and shell, and the contents of the\fB.project\fRand\fB.plan\fRfiles in the home directory:.nf    Directory: /dd/USR/TESTER      Shell: shell    Project: <none>    No plan..fiGiven\fIuser\fR@\fIhost\fRit asks that machine instead, over the network..SH SEE ALSOlogname