.TH WHAT 1.SH NAMEwhat \- list the cards in a GEPARD.SH SYNOPSIS\fBwhat\fR.SH DESCRIPTIONAn inventory tool for the GEPARD, the German 68000 machine much of theEFFO software was written on.  It prints\fBWhat's where in the GEPARD:\fRand a table of the expansion cards it finds -- I/O address, referencebyte and the card's name.  On any other machine the table is empty.  Itignores its arguments..SH NOTESYour own OS-9 may have a utility of this name; see\fBDOC/README-NAMES\fR.\fR