.TH MORSE 6.SH NAMEmorse \- write text as Morse code.SH SYNOPSIS\fBmorse\fR[\-s] [string ...].SH DESCRIPTION\fBmorse\fRwrites its arguments, or its standard input, as Morse code, one letter toa line: in words,\fBdit dit dit,\fR,\fRor with\fB\-s\fRin dots and dashes,\fB...,\fRFrom 4.3BSD Net/2.