.TH MIMECODE 1.SH NAMEmimecode \- base64 encoding, MIME's.SH SYNOPSIS\fBmimecode\fR\-e|\-d < infile > outfile.SH DESCRIPTION\fBmimecode\fRtranslates its standard input to its standard output:\fB\-e\fRencodes any file as base64, printable text safe to mail;\fB\-d\fRturns base64 back into the original bytes.  A line of `hello' encodes as\fBaGVsbG8N\fR-- the last character carrying OS-9's carriage return.  Tim Kientzle's,from Dr. Dobb's Journal, September 1995..SH SEE ALSOuuencode, btoa