.TH CHARCNT 1.SH NAMEcharcnt \- count each character in a file.SH SYNOPSIS\fBcharcnt\fRfile ....SH DESCRIPTION\fBcharcnt\fRreads the files named and prints a table of all 128 ASCII codes withhow many times each occurred, eight columns of sixteen, controlcharacters shown by name\fR(\fBNU\fR,\fR\fB^A\fR,\fR\fBCR\fR,\fR\fBES\fR,\fR\fBSP\fR,\fR\fBDL\fR),\fRand then\fBTotal # of chars read\fRfor the lot.  It is the quick way to see whether a file has line feedsin it, or tabs, or anything it should not..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOwc, unp, dump