.TH NNTIDY 1 "Release 6.3".UC 4.SH NAMEnntidy \- tidy your personal \fInn\fP(1) rc file.SH SYNOPSIS.B nntidy.SH DESCRIPTION.B nntidywill clean out non-existing groups, adjust obviously wrong articlenumbers, and remove badly formed lines from your rc file..LPIt will also sort the lines in the rc file in alphabetical order..LPYou should run .B nntidyif your rc file has been corrupted for some reason..SH FILES.DT.ta \w'~/.nn/rc.bak'u+3m.\"ta 0 20~/.nn/rc	The record of read articles.br~/.nn/rc.bak	The original rc file before tidy.DT.SH SEE ALSOnn(1), nncheck(1), nngoback(1), nngrep(1).brnnadmin(1M), nnquery(1M), nnusage(1M), nnmaster(8).SH AUTHORKim F. Storm, Texas Instruments A/S, Denmark.brE-mail: storm@texas.dk