.TH pbmtoln03 1 "7 May 1993".IX pbmtoln03.SH NAMEpbmtoln03 - convert protable bitmap to DEC LN03+ Sixel output.SH SYNOPSIS.B pbmtoln03.RB [ -rltbf ].I pbmfile.SH DESCRIPTIONReads a portable bitmap as input..IX "DEC LN03+ Sixel"Produces a DEC LN03+ Sixel output file..SH OPTIONS.TP.B -l nnUse "nn" as value for left margin (default 0)..TP.B -r nnUse "nn" as value for right margin (default 2400)..TP.B -t nnUse "nn" as value for top margin (default 0)..TP.B -b nnUse "nn" as value for bottom margin (default 3400)..TP.B -f nnUse "nn" as value for form length (default 3400)..SH "SEE ALSO"pbm(5).SH AUTHORTim Cook, 26 Feb 1992