.TH pbmtolps "12 Dec 1990".SH NAMEpbmtolps - convert portable bitmap to PostScript.SH SYNOPSISpbmtolps [ -dpi n ] [ pbmfile ].SH DESCRIPTIONReads a portable bitmap as input, and outputs PostScript.The output Postscript uses lines instead of the image operator togenerate a (device dependent) picture which will be imagedmuch faster..PPThe Postscript path length is constrained to be less that 1000points so that no limits are overrun on the Apple Laserwriterand (presumably) no other printers..SH "SEE ALSO"pgmtops(1), ppmtops(1), pbm(5).SH AUTHORGeorge Phillips <phillips@cs.ubc.ca>