.TH globe 1 "26 March 1994".SH NAMEglobe - display the currently-lighted face of Earth in ASCII.SH SYNOPSIS.B globe.SH DESCRIPTION.PPA cute ASCII graphic hack.  The pictures were converted from 256x256bitmaps using pbmtoascii.  The bitmaps originally came from Sun.  Thewrapper program took 20 minutes to write, including documentation..SH AUTHORCopyright (C) 1994 by Jef Poskanzer <jef@netcom.com>..\" Permission to use, copy, modify, and distribute this software and its.\" documentation for any purpose and without fee is hereby granted, provided.\" that the above copyright notice appear in all copies and that both that.\" copyright notice and this permission notice appear in supporting.\" documentation.  This software is provided "as is" without express or.\" implied warranty.