.TH TTYEXP 6.SH NAMEttyexp \- fireworks in characters.SH SYNOPSIS\fBttyexp\fR[\-s\fIn\fR] [\-p\fIn\fR] [\-x\fIn\fR] [\-y\fIn\fR] [\-t\fIn\fR] [\-g\fIn\fR] [\-w\fIn\fR] [\-d\fIn\fR] [\-c\fIc\fR] [\-D\fIn\fR].SH DESCRIPTIONFireworks: bursts of characters thrown out from a point, arcing undergravity with trails behind them, for ten seconds, and then the screen iscleared.\fBttyexp \-s2 \-p50\fRfills the screen.  It draws with VT100 sequences through TERMCAP..SH OPTIONS.TP 12\fB\-s\fIn\fRbursts at once; 1..TP 12\fB\-p\fIn\fRpoints in each burst, up to 300; 10..TP 12\fB\-x\fIn\fB, \-y\fIn\fRthe size of a burst; 40 by 15..TP 12\fB\-t\fIn\fRtrail length; 4..TP 12\fB\-g\fIn\fRgravity; 1000..TP 12\fB\-w\fIn\fRwind; 0..TP 12\fB\-d\fIn\fRdelay factor; 0..TP 12\fB\-c\fIc\fRthe character; @..TP 12\fB\-D\fIn\fRseconds to run; 10..SH SEE ALSOrain, worms