.TH SNAPSHOT 1.SH NAMEsnapshot \- make a snapshot of the terminal screen into a file.SH SYNOPSIS.B snapshot[.B \-s start] [.B \-e end].B destfile.br.B snapshot \-l.SH DESCRIPTION.I Snapshotmakes a copy of the terminal screen (optionally, only certain lines of it;see below) in the specified file.  It strips any trailing spaces from theend of each line..PPOptions:.TP.I \-s startuse.I startas the starting line instead of the default (usually 0 or 1)..TP.I \-e enduse.I endas the ending line instead of the default (usually 24)..TP.I \-llist the known terminal types.SH BUGSOnly works on certain terminals.  Also, the last character in 80-columnwide lines is replaced with a newline so that the file can be easilyedited..SH AUTHORDavid MacKenzie