.TH THEOREM 6.SH NAMEtheorem \- four programs in one obfuscated source.SH SYNOPSIS\fBtheorem\fRexpr x1 x2 h y1.br\fBtheorem \-r\fR0 0 0 0.SH DESCRIPTIONThe 1990 International Obfuscated C Code Contest's Best of Show, whoseone source is four programs.  Given an expression in\fBx\fRand\fBy\fRand the start, end, step and starting value, it solves the differentialequation y'=f(x,y) by the Runge-Kutta method and prints x and y a stepat a time:\fBtheorem y 0 1 0.1 1\fRends at 2.718280, which is e.  With\fB\-r\fRit reverses its standard input instead..SH SEE ALSOdds, westley