.TH SQRTX 1.SH NAMEsqrtx \- square roots, and how far they miss.SH SYNOPSIS\fBsqrtx\fR.SH DESCRIPTION\fBsqrtx\fRprints a table of square roots of the numbers that are not perfectsquares: the number, its root, the root squared again to seventeenplaces, and the difference between that and the number -- the roundingerror of the floating-point arithmetic..nf        2 1.41421   2.00000000000000000   4.44e-16        5 2.23607   5.00000000000000100  -8.88e-16.fi.SH SEE ALSOsavage, paranoia