.TH UPPERDIR 1.SH NAMEupperdir \- normalise the case of names in a directory.SH SYNOPSIS\fBupperdir\fR[directory].SH DESCRIPTION\fBupperdir\fRrenames everything in a directory, the current one unless named: filesto lower case, directories to upper case, the convention many OS-9systems follow.  It prints each new name as it goes.