.TH CALCDATE 1.SH NAMEcalcdate \- add days to a date, or count days between two.SH SYNOPSIS\fBcalcdate\fRmmddyy \-o [\-]offset.br\fBcalcdate\fRmmddyy \-d mmddyy.SH DESCRIPTIONDates are six digits,\fImmddyy\fR.\fR\fBcalcdate 051788 \-o 30\fRprints the date thirty days on,\fB061688\fR;\fRa negative offset goes back.\fBcalcdate 010188 \-d 123188\fRprints the number of days from one to the other,\fB365\fR.\fRVersion 2.01, Gordon A. Runkle, 1988..SH SEE ALSOweekday, cal