.TH PRIMES 6.SH NAMEprimes \- the primes between two numbers.SH SYNOPSIS\fBprimes\fR[start [stop]].SH DESCRIPTION\fBprimes\fRprints the prime numbers from\fIstart\fRto\fIstop\fR,\fRone to a line, with a sieve:\fBprimes 1 30\fRprints 2, 3, 5 and so on to 29.  From 4.3BSD Net/2..SH SEE ALSOfactor, sieve