.TH PSYCHIC 6.SH NAMEpsychic \- a fortune teller.SH SYNOPSIS\fBpsychic\fR[count].SH DESCRIPTION\fBpsychic\fRprints psychic messages, three unless you give a number, each strungtogether at random from stock phrases of prophecy:.nf    Run this program again, and find that you will change your    name three times in the next three years..fi.SH SEE ALSOfortune