.TH CHOOSE 1 "7 August 1985".UC 4.SH NAMEchoose \- randomly select one or more lines.SH SYNOPSIS.B choose[.BI \- n][.I file ...].SH DESCRIPTION.I Chooserandomly chooses lines from its input.IR file s(default: standard input).All such files are concatenated together before the selection takesplace..PPThe command line option is:.TP.BI \- nSelect.I nlines from the input (default: 1)..SH EXAMPLETo build your own version of.IR fortune (1),put each saying in a file in the directory "wisdom" and then execute.IPcat `ls wisdom/* | choose`.SH FILES/tmp/choose.*.SH AUTHORBob Lewis, CAE Systems Division, Tektronix