.TH FONTGEN 1.SH NAMEfontgen \- generate a font for the Gepard display.SH SYNOPSIS\fBfontgen\fR> font.a.SH DESCRIPTION\fBfontgen\fRwrites, on the standard output, the assembler source of an 80-columncharacter font for the GEPARD's display card: a data module\fR(\fBtext80z.font\fR)\fRof\fBdc.w\fRlines.  Assemble it with Microware's assembler to get the module.