.TH BANNER1 1.SH NAMEbanner1 \- print text in large letters.SH SYNOPSIS\fBbanner1\fR[\-id] [\-c=char] [\-s] [\-z[=file]] string ....SH DESCRIPTION\fBbanner1\fRprints its arguments as letters eight rows high, built of asterisks.Written by Wolfgang Ocker in 1987, it was the first banner program onOS-9/68000, and its source builds on Unix as well..SH OPTIONS.TP 12\fB\-d\fRdouble size..TP 12\fB\-i\fRitalic: the letters slant..TP 12\fB\-c=\fIchar\fRbuild the letters from\fIchar\fRinstead of asterisks..TP 12\fB\-s\fRbuild each letter out of itself..TP 12\fB\-z\fRread the strings from the standard input, or with\fB\-z=\fIfile\fRfrom\fIfile\fR.\fR.SH SEE ALSOgothic, banner