.TH PPT 6.SH NAMEppt \- punch text onto paper tape.SH SYNOPSIS\fBppt\fR[string ...].SH DESCRIPTION\fBppt\fRdraws its arguments, or its standard input, as a strip of punched papertape running down the screen: one row of holes\fR(\fBo\fR)\fRfor each character's bits, with the sprocket hole\fR(\fB.\fR)\fRdown the middle.  From 4.3BSD Net/2..SH SEE ALSOmorse, bcd