.TH TAIL 1.SH NAMEtail \- the last lines of a file.SH SYNOPSIS\fBtail\fR[\-l=n] file ....SH DESCRIPTION\fBtail\fRprints the last twenty lines of each text file named, or the last\fIn\fRwith\fB\-l=\fIn\fR:\fR\fBtail \-l=3 log\fR.\fRThe name may be a wildcard.  DESIGNA VLT, UTIL 2.70..SH OPTIONS.TP 12\fB\-l=\fIn\fRthe last\fIn\fRlines..TP 12\fB\-d\fRdebugging output..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOhead, tac