.TH DUMP 1 Terminfo/Curses.SH NAMEdump \- Print the contents of a compiled terminfo file in human-readable form.SH SYNOPSIS.B /etc/term/dump file ....SH DESCRIPTION.I Dump reads the given files and decodes their contents to derive a reasonablerepresentation of the terminfo entry which produced the file originally.It should be noted, in case of emergency, that the output of.I dumpis perfectly usable as the input to.IR compile (1)..SH SEE ALSOcompile(1), term(5), terminfo(5).SH AUTHORPavel Curtis, Cornell University.br(decvax!cornell!pavel or Pavel.Cornell@Udel-Relay)