.TH RAIN 6.SH NAMErain \- raindrops on the screen.SH SYNOPSIS\fBrain\fR.SH DESCRIPTIONRaindrops land at random on the screen and spread outward in rings,five at a time, until you stop it with control-C.  A screen toy, byEric P. Scott of Caltech, 1980.  It draws through TERMCAP, so it needsTERM and TERMCAP set..SH SEE ALSOworms, xmas