.TH CHBASE 1.SH NAMEchbase \- convert a number between bases.SH SYNOPSIS\fBchbase\fRnumber [from [to]].SH DESCRIPTION\fBchbase\fRreads\fInumber\fRin base\fIfrom\fR,\fR10 unless given, and prints it in base\fIto\fR,\fR16 unless given.  A\fIto\fRof 0 prints it in every base from 2 to 36..nf    chbase 255              255 [10] = FF [16]    chbase 255 10 2         255 [10] = 11111111 [2]    chbase ff 16 10         ff [16] = 255 [10].fiBy Philip Maechler..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOcvtbase, bc