.TH SCREENS 6 "Local Manual                 7/19/88".SH NAMEscreens \- Random screen displayer.SH SYNOPSIS.B screens.SH DESCRIPTION.I Screens scans your.BI $HOME/.screensdirectory, and picks a random file to displayon the screen.  If the filename ends with.I .g,it turns on z29a graphicsmode first..SH FILES$HOME/.screens/*.SH BUGSIf you have some mutant terminal type which starts with z but isn't zenithgraphics compatible,.B screensmay select a zenith screen (if you have one)..SH AUTHORRuss Smith