.TH LS 1.SH NAMEls \- list directory contents.SH SYNOPSIS\fBls\fR[option ...] [file ...].SH DESCRIPTION\fBls\fRis GNU ls, from fileutils 3.13, built from\fBSRC/ls\fR.\fRIt lists the files named, or the current directory, in columns, sortedby name.\fBls \-l\fRgives the long form: permissions, link count, owner, size, date andname.\fBls \-\-help\fRgives every option; the common ones are\fB\-a\fR(all, including names beginning with a dot),\fB\-l\fR(long),\fB\-t\fR(sort by time),\fB\-r\fR(reverse),\fB\-R\fR(recursive),\fB\-d\fR(a directory as itself),\fB\-i\fR(a number unique to each file) and\fB\-F\fR(mark directories and programs)..SH SEE ALSOdir