.TH LOGNAME 1.SH NAMElogname \- print the login name.SH SYNOPSIS\fBlogname\fR.SH DESCRIPTION\fBlogname\fRis GNU logname, from sh-utils 1.10.  It prints the name that\fB/dd/SYS/password\fRgives for the group.user number the process is running as.  That is notnecessarily the name in\fBUSER\fR:\fRunder this disk's\fBSYS/login\fR,\fRwhich sets\fBUSER\fRto\fBtester\fRwhile the process still runs as 0.0, it answers\fBsu\fR,\fRthe first name the password file gives to 0.0..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOwhoami, su