.TH WEEKDAY 1.SH NAMEweekday \- facts about a date.SH SYNOPSIS\fBweekday\fR[\-svdDmMywjnah] [date].SH DESCRIPTION\fBweekday\fRtells you the day of the week, the day of the year and the week numberof a date, today unless one is given:.nf    weekday 10/30/89    30 October 1989 is on a Monday on julian day 303 in week 44.fiA date is\fImm/dd/yy\fR,\fR\fIdd-mm-yy\fR,\fR\fIyyyy-mm-dd\fR,\fR\fIyy.ddd\fRor a Unix date..SH OPTIONSEach prints one fact alone:\fB\-d\fRthe day of the week as a number,\fB\-D\fRas a name,\fB\-m\fRthe month's number,\fB\-M\fRits name,\fB\-y\fRthe year,\fB\-w\fRthe week,\fB\-j\fRthe day of the year,\fB\-n\fRthe day of the month.\fB\-a\fRis everything, the default;\fB\-s\fRand\fB\-v\fRtoggle the short and the verbose forms.