.TH DDS 6.SH NAMEdds \- a BASIC interpreter in 1536 characters.SH SYNOPSIS\fBdds\fR.SH DESCRIPTIONA BASIC interpreter written in 1536 characters of obfuscated C, theBest Language Tool of the 1990 International Obfuscated C Code Contest.It prompts\fBOk\fR.\fRType numbered lines to enter a program;\fBRUN\fR,\fR\fBLIST\fR,\fR\fBNEW\fR,\fR\fBOLD\fR,\fR\fBSAVE\fRand\fBBYE\fRact at once.  Variables are\fBa\fRto\fBz\fR;\fR\fBFOR\fR,\fR\fBGOSUB\fR,\fR\fBGOTO\fR,\fR\fBIF\fR,\fR\fBINPUT\fRand\fBPRINT\fRwork.  Type keywords in capitals..SH SEE ALSOtheorem, westley, basic