#!/usr/bin/env python3
"""Programs that open a file BY BARE NAME, and where that file actually is.

    tools/bare_deps.py disk
    tools/bare_deps.py disk --all      # include the doubtful ones

WHY THIS EXISTS.  `DOC/DEPENDS' is generated by scanning binaries for ABSOLUTE
paths, and a program that opens `kepler.dat' rather than `/h0/kepler.dat' is
invisible to it.  That is not a rare shape: OS-9 gives a process a DATA
DIRECTORY, and opening a data file by bare name relative to it is the normal
thing for a program of this era to do.

It cost real time.  `orbit' -- the N3EMO satellite tracker -- was written up as
wanting an element file "no archive here carried", and `advcom' as needing a
shell with a real `chd'.  Neither was true.  kepler.dat, mode.dat and three
site files are in DOC/orbit; osample.adv and objects.adi are in GAMES/ADVSYS.
Both programs work as soon as their files are where the data directory is, and
both now have a card and a test that do exactly that.  Nothing pointed at
either of them, because DEPENDS could not see a name without a slash.

WHAT IT CANNOT DO.  A string in a binary is not proof it is opened -- it may be
a message, or `__FILE__' baked in by the compiler.  That last one is why the
output is in two parts: hits whose extension says DATA (.dat .hlp .ps .book
.fmt .inc .err .mk) are reported first and are usually real; hits on source
extensions (.c .h) are held back behind --all, because `yacc' naming lalr.c and
`grep' naming dfa.c are their own source files, not files they look for.

Nor does it prove the file it found is THE file the program wants -- gnuchess
naming gnuchess.book and a gnuchess.book existing under USR/src/chess is a
strong hint and not a fact.  Read it as a list of things to go and try.
"""

import os
import re
import sys

# name.ext, NUL-terminated, not part of a longer path.
BARE = re.compile(rb"(?<![A-Za-z0-9_./-])([a-z][a-z0-9_-]{1,14}\.[a-z]{1,4})\0")
MODULE = b"\x4a\xfc"
# Extensions that mean "a file this program reads", not "a file it was built
# from".  Anything outside this list is reported only under --all.
DATA_EXT = {".dat", ".hlp", ".ps", ".book", ".fmt", ".base", ".inc", ".err",
            ".mk", ".out", ".net", ".okn", ".mbox", ".log", ".sav", ".type",
            ".pil", ".cmd", ".tfm", ".data", ".sit", ".adv", ".adi", ".txt",
            ".cfg", ".ini", ".def", ".tbl", ".idx"}


def index(root):
    """Every file under `root', keyed by lower-case basename."""
    found = {}
    # SORTED WALKS, here and in scan(): os.walk follows the filesystem's
    # own order, which APFS and ext4 do not share, so CI on Linux wrote a
    # different DOC/DEPENDS from the same tree (2026-09-26).  Where a name
    # is in two places, the first in sorted order is the one named.
    for base, dirs, files in os.walk(root):
        dirs.sort()
        for f in sorted(files):
            found.setdefault(f.lower(), []).append(os.path.join(base, f))
    return found


def wants(path):
    """The bare filenames a module names and does not also name with a path."""
    with open(path, "rb") as f:
        blob = f.read()
    if blob[:2] != MODULE:
        return set()
    return {m.group(1) for m in BARE.finditer(blob)
            if b"/" + m.group(1) not in blob}


def scan(root, everything=False):
    """(program, filename, where it is) for each bare name that exists."""
    here = index(root)
    rows = []
    for base, dirs, files in os.walk(os.path.join(root, "CMDS")):
        dirs.sort()
        for f in sorted(files):
            path = os.path.join(base, f)
            try:
                names = wants(path)
            except OSError:
                continue
            for raw in sorted(names):
                name = raw.decode()
                if not everything and os.path.splitext(name)[1] not in DATA_EXT:
                    continue
                for where in here.get(name.lower(), []):
                    rows.append((os.path.relpath(path, root), name,
                                 os.path.relpath(where, root)))
                    break
    return rows


def main(argv):
    root = next((a for a in argv if not a.startswith("-")), None)
    if not root or not os.path.isdir(os.path.join(root, "CMDS")):
        sys.exit(__doc__)
    rows = scan(root, "--all" in argv)
    print("%d bare-name dependencies whose file is on the disk%s\n"
          % (len(rows), "" if "--all" in argv else " (data extensions only)"))
    for prog, name, where in rows:
        print("  %-30s wants %-18s -> %s" % (prog[len("CMDS/"):], name, where))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
