.TH LIBSPLIT 1.SH NAMElibsplit \- split a new-style library into ROF files.SH SYNOPSIS\fBlibsplit\fR[\-r] [\-@] library ....SH DESCRIPTION\fBlibsplit\fRtakes a linker library in the newer, typed format apart, writing eachpsect it holds to a relocatable object file of its own.  By MichaelLamparth, 1998..SH OPTIONS.TP 12\fB\-r\fRoverwrite a ROF file that exists..TP 12\fB\-@\fRdebugging output..SH SEE ALSOunpacklib, liborder