.TH GOTHIC 1.SH NAMEgothic \- print text as a blackletter banner.SH SYNOPSIS\fBgothic\fRstring ....SH DESCRIPTION\fBgothic\fRprints its arguments in large gothic letters built of\fBO\fRs,\fRfor a printer to run off as a banner..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSObanner1