.TH GETENV 1.SH NAMEgetenv \- test or print an environment variable.SH SYNOPSIS\fBgetenv\fR[\-n|\-p|\-l|\-x] name [value].SH DESCRIPTION\fBgetenv\fRtests whether the variable\fIname\fRis set -- or, given a\fIvalue\fR,\fRwhether it has that value -- and answers in its exit status, 0 for yes,for use in a script.  Its own help is in German.  DESIGNA VLT, UTIL 2.40..SH OPTIONS.TP 12\fB\-n\fRinvert the answer..TP 12\fB\-p\fRprint the value, with a line end..TP 12\fB\-l\fRprint the value, without one..TP 12\fB\-x\fRexit with the value as the status..SH EXAMPLES.nfgetenv -p TERM                xterm-256colorgetenv TERM vt100             status 1 unless TERM is vt100getenv -n TERM vt100          status 0 unless it is.fi.SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOprintenv, checkenv