.TH EPSON 1.SH NAMEepson \- set up an Epson printer.SH SYNOPSIS\fBepson\fR[\-c\fIn\fR] [\-g|\-u] [\-p] [\-n] < infile > printer.SH DESCRIPTION\fBepson\fRcopies text to an Epson dot-matrix printer, putting the control codesin front that set it up:.TP 12\fB\-c\fIn\fRcharacters per inch: 10, 12 or 17..TP 12\fB\-g\fRthe German character set..TP 12\fB\-u\fRthe ASCII character set..TP 12\fB\-p\fRa form feed..TP 12\fB\-n\fRnormal: ASCII at 17 characters per inch..PPIt came with Paul Farquhar's spline package, whose plots it prints..SH NOTESNeeds Microware's\fBcio\fR.\fR.SH SEE ALSOlmargin, spline