.TH WISECRACK 6.SH NAMEwisecrack, ask \- a slogan server and its client.SH SYNOPSIS\fBwisecrack &\fR.br\fBask\fR[anything].SH DESCRIPTION\fBwisecrack\fRis a server: started in the background it writes slogans, one at a time,into the named pipe\fB/pipe/txtpipe\fR.\fR\fBask\fRis its client: each call reads the next line out of the pipe and printsit.  The slogans are in German, from an OS-9 seminar of 1992-93:.nf    $ wisecrack &    $ ask    VIEL SPASS MIT OSK    $ ask    COMPUTER-VEREIN E.V.fiWith no server running,\fBask\fRanswers\fBNo Wisecracks coming\fR.\fRStop the server with\fBkill\fRor\fBsignal\fRwhen you are done..PPThe pair is an example of OS-9 named pipes -- one process writing, anynumber reading.